import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./(auth)/context";

import 'react-toastify/ReactToastify.min.css'
import Notification from "./components/toast";
import { UploadTopicProvider } from "./(admin)/researcher/validation/context";
import { AppointmentsProvider } from "./(admin)/researcher/meeting/context";
import { ResearcherProfileProvider } from "./(admin)/researcher/profile/context";
import { DocumentProvider } from "./(admin)/researcher/upload/context";
import { SupervisorProfileProvider } from "./(admin)/supervisor/context";


// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Researcher Corridor",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {


    return (
        <html lang="en">
            <body>
                <UploadTopicProvider>
                    <AppointmentsProvider>
                        <DocumentProvider>
                            <AuthProvider>
                                <Notification />
                                {children}
                            </AuthProvider>
                        </DocumentProvider>
                    </AppointmentsProvider>
                </UploadTopicProvider>

            </body>
        </html>
    );
}
