import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./(auth)/context";

import 'react-toastify/ReactToastify.min.css'
import Notification from "./components/toast";
import { UploadTopicProvider } from "./(admin)/researcher/validation/context";
import { AppointmentsProvider } from "./(admin)/supervisor/appointment/context";
import { ResearcherProfileProvider } from "./(admin)/researcher/profile/context";
import { DocumentProvider } from "./(admin)/researcher/upload/context";
import { SupervisorProfileProvider } from "./(admin)/supervisor/context";
import { NotificationsProvider } from "./(admin)/researcher/notificaton/context";
import { SupervisorDocumentsProvider } from "./(admin)/supervisor/document/context";
import { GradesProvider } from "./(admin)/supervisor/grade/context";
import { ProgressProvider } from "./(admin)/supervisor/progress/context";
import { AssignedResearchersProvider } from "./(admin)/supervisor/researcher/context";
import { ValidationRequestsProvider } from "./(admin)/supervisor/validation/context";


// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Researcher Corridor",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {


    return (
        <html lang="en">
            <body>
                {/* <ChatProvider> */}

                <AssignedResearchersProvider>
                    <SupervisorDocumentsProvider>
                        <ValidationRequestsProvider>
                            <GradesProvider>
                                <NotificationsProvider>
                                    <ProgressProvider>
                                        <ResearcherProfileProvider>
                                            <SupervisorProfileProvider>
                                                <UploadTopicProvider>
                                                    <AppointmentsProvider>
                                                        <DocumentProvider>
                                                            <AuthProvider>
                                                                <Notification />
                                                                {children}
                                                            </AuthProvider>
                                                        </DocumentProvider>
                                                    </AppointmentsProvider>
                                                </UploadTopicProvider>
                                            </SupervisorProfileProvider>
                                        </ResearcherProfileProvider>

                                    </ProgressProvider>

                                </NotificationsProvider>
                            </GradesProvider>

                        </ValidationRequestsProvider>

                    </SupervisorDocumentsProvider>

                </AssignedResearchersProvider>

                {/* </ChatProvider> */}

            </body>
        </html>
    );
}
