import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./(auth)/context";
import { DocumentProvider } from "./(admin)/admin/upload/context";
import { UploadTopicProvider } from "./(admin)/admin/validation/context";


// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Researcher Corridor",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <UploadTopicProvider>

                    <DocumentProvider>
                        <AuthProvider>
                            {children}
                        </AuthProvider>
                    </DocumentProvider>

                </UploadTopicProvider>

            </body>
        </html>
    );
}
